#!/bin/sh

set -eu
set -o pipefail

exec 3>&1 # fd 3 is used to output the json result
exec 1>&2 # redirect stdout to stderr so it doesn't interfere with the json

PAYLOAD=$(mktemp graphite-event-resource.XXXXXX)
cat > "$PAYLOAD" <&0

WHAT=$(jq --raw-output .params.what < "$PAYLOAD")
# Expand variables for $BUILD_ID, $BUILD_NAME, etc.
WHAT=$(eval echo "$WHAT")
TAGS=$(jq --raw-output .params.tags < "$PAYLOAD")
TAGS=$(eval echo "$TAGS")
DATA=$(jq --raw-output .params.data < "$PAYLOAD")
DATA=$(eval echo "$DATA")

jq \
  --null-input \
  --arg what "$WHAT" \
  --arg tags "$TAGS" \
  --arg data "$DATA" \
  '{"what" : $what, "tags" : $tags, "data" : $data}' \
  | \
  curl \
    --verbose \
    "$(jq --raw-output .source.url < "$PAYLOAD")/events/" \
    --data @-

rm "$PAYLOAD"

jq \
  --null-input \
  --arg time "$(date +'%s')" \
  '{ "version" : { "time" : $time } }' \
  >&3
